export const careers = [
    {
      id: 1,
      title: "Data Scientist",
      category: "Technology",
      salaryRange: "$75K - $120K",
      growthRate: 22,
      description: "Analyze complex data sets to identify trends and insights that drive business decisions. Work with machine learning models and statistical analysis.",
      skills: ["Python", "Statistics", "SQL", "Machine Learning", "Data Visualization"],
    },
    {
      id: 2,
      title: "Physical Therapist",
      category: "Healthcare",
      salaryRange: "$65K - $95K",
      growthRate: 18,
      description: "Help patients recover from injuries and manage pain through exercises, hands-on therapy, and education about how to prevent future injuries.",
      skills: ["Anatomy", "Patient Care", "Rehabilitation", "Assessment", "Communication"],
    },
    {
      id: 3,
      title: "Marketing Manager",
      category: "Business",
      salaryRange: "$60K - $110K",
      growthRate: 10,
      description: "Plan and oversee marketing campaigns, analyze market trends, and develop strategies to promote products or services and drive business growth.",
      skills: ["Digital Marketing", "Analytics", "Content Strategy", "Project Management", "Communication"],
    },
    {
      id: 4,
      title: "UX/UI Designer",
      category: "Creative",
      salaryRange: "$55K - $90K",
      growthRate: 13,
      description: "Create intuitive, accessible, and enjoyable digital experiences for users while balancing business needs and technical constraints.",
      skills: ["User Research", "Wireframing", "Prototyping", "Visual Design", "Figma"],
    },
    {
      id: 5,
      title: "Educational Counselor",
      category: "Education",
      salaryRange: "$45K - $70K",
      growthRate: 8,
      description: "Guide students through academic and career decisions, helping them navigate educational paths and overcome barriers to success.",
      skills: ["Counseling", "Assessment", "Communication", "Problem-Solving", "Empathy"],
    },
    {
      id: 6,
      title: "Environmental Scientist",
      category: "Science",
      salaryRange: "$65K - $100K",
      growthRate: 8,
      description: "Identify, assess, and address environmental problems such as pollution and ecosystem degradation through research and policy recommendations.",
      skills: ["Research", "Data Analysis", "Fieldwork", "Technical Writing", "GIS"],
    },
    {
      id: 7,
      title: "Software Engineer",
      category: "Technology",
      salaryRange: "$80K - $150K",
      growthRate: 21,
      description: "Design, develop, and maintain software applications and systems using various programming languages and technologies.",
      skills: ["JavaScript", "Java", "Python", "System Architecture", "Problem Solving"],
    },
    {
      id: 8,
      title: "Registered Nurse",
      category: "Healthcare",
      salaryRange: "$60K - $90K",
      growthRate: 12,
      description: "Provide and coordinate patient care, educate patients about health conditions, and provide advice and emotional support to patients and families.",
      skills: ["Patient Care", "Medical Knowledge", "Communication", "Critical Thinking", "Empathy"],
    },
    {
      id: 9,
      title: "Financial Analyst",
      category: "Business",
      salaryRange: "$65K - $105K",
      growthRate: 9,
      description: "Analyze financial data, prepare reports, and make recommendations to help businesses make informed investment decisions.",
      skills: ["Financial Modeling", "Excel", "Data Analysis", "Research", "Communication"],
    },
    {
      id: 10,
      title: "Graphic Designer",
      category: "Creative",
      salaryRange: "$45K - $80K",
      growthRate: 7,
      description: "Create visual concepts to communicate ideas that inspire, inform, and captivate consumers using various design elements.",
      skills: ["Adobe Creative Suite", "Typography", "Color Theory", "Layout Design", "Branding"],
    },
    {
      id: 11,
      title: "Special Education Teacher",
      category: "Education",
      salaryRange: "$48K - $75K",
      growthRate: 6,
      description: "Work with students who have a wide range of learning, mental, emotional, and physical disabilities to adapt general education lessons.",
      skills: ["Specialized Instruction", "IEP Development", "Patience", "Communication", "Assessment"],
    },
    {
      id: 12,
      title: "Biomedical Engineer",
      category: "Science",
      salaryRange: "$70K - $115K",
      growthRate: 10,
      description: "Analyze and design solutions to problems in biology and medicine with the goal of improving health and quality of life.",
      skills: ["CAD", "Materials Science", "Biology", "Problem Solving", "Programming"],
    },
  ];